-- Projeler tablosu
CREATE TABLE projects (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  title TEXT NOT NULL,
  description TEXT NOT NULL,
  image TEXT NOT NULL,
  demo_url TEXT,
  github_url TEXT,
  technologies TEXT[] NOT NULL,
  category TEXT NOT NULL,
  featured BOOLEAN NOT NULL DEFAULT false,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Yetenekler tablosu
CREATE TABLE skills (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL,
  icon TEXT NOT NULL,
  category TEXT NOT NULL
);

-- Deneyim tablosu
CREATE TABLE experiences (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  company TEXT NOT NULL,
  position TEXT NOT NULL,
  start_date TEXT NOT NULL,
  end_date TEXT,
  description TEXT NOT NULL,
  technologies TEXT[] NOT NULL
);

-- Eğitim tablosu
CREATE TABLE education (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  institution TEXT NOT NULL,
  degree TEXT NOT NULL,
  field TEXT NOT NULL,
  start_date TEXT NOT NULL,
  end_date TEXT
);

-- İletişim bilgileri tablosu
CREATE TABLE contact (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  email TEXT NOT NULL,
  github TEXT,
  linkedin TEXT,
  twitter TEXT
);

-- RLS Politikaları (Row Level Security)
-- Herkes okuyabilir, yazma izni yok

-- Projeler için politikalar
ALTER TABLE projects ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Herkes projeleri okuyabilir" ON projects FOR SELECT USING (true);

-- Yetenekler için politikalar
ALTER TABLE skills ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Herkes yetenekleri okuyabilir" ON skills FOR SELECT USING (true);

-- Deneyim için politikalar
ALTER TABLE experiences ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Herkes deneyimleri okuyabilir" ON experiences FOR SELECT USING (true);

-- Eğitim için politikalar
ALTER TABLE education ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Herkes eğitim bilgilerini okuyabilir" ON education FOR SELECT USING (true);

-- İletişim için politikalar
ALTER TABLE contact ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Herkes iletişim bilgilerini okuyabilir" ON contact FOR SELECT USING (true); 