---
deployment:
  tasks:
    - export DEPLOYPATH=/home/u2255410/repositories/my-portfolio
    - /bin/cp -R .next $DEPLOYPATH
    - /bin/cp -R public $DEPLOYPATH
    - /bin/cp -R src $DEPLOYPATH
    - /bin/cp package.json $DEPLOYPATH
    - /bin/cp next.config.ts $DEPLOYPATH
    - /bin/cp tailwind.config.js $DEPLOYPATH
    - /bin/cp postcss.config.mjs $DEPLOYPATH
